### ISSUE TITLE
its not say for permissions..

### ISSUE THREAD

**Issue by ideepsrma** [RohitRajP/statusForever#1]
Now your source code not working, 
its not saying for permissions , i bypass it via simple_permissions plugin , after that its not fetch_status

i tried whole day to figure out , but can't success...

i you have time please recheck it.....

**Comment by RohitRajP** [comment]
**Hi ideepsrma,**

Thank you for raising this issue as I was not aware of the inability to recompile code after cloning.

**Reason for "source code not working":**
When we upload an application to Google PlayStore, we sign the app using some private credentials
These private credentials should not be pushed to public repository and thus the "key.properties" file is added to the gitignore file. So, during compilation, the gradle was expecting the key file, which, caused the compiler to raise an exception.

**Solution for "source code not working":**
I have defaulted the gradle to compile to debug instead of release, so now it does not expect any key file and will execute promptly I hope.

**Concerning the issue of app not asking permissions**, I have not made use of any plugins for permissions and I handle that using native code. I have myself experienced this bug, especially in older versions of android. I am currently unaware of the reason of occurance, but I am planning to offload the permission handling functionality to a third-party plugin like simple_permissions, as you have mentioned. 
If the issue is of urgency, please do let me know so that I can make the modification as quick as possible.

**Comment by ideepsrma** [comment]
Thanks for reply sir,

Sir am using your code in debug mode becoz now m only checking. So i
changed it to debug and comment the key values in gradle file,,


After giving permission its open a blank screen with appBar "Status Forever"

-I using only dart files from your "lib" folder
-I testing on my samsung m20
-VScode for devloping

**Comment by RohitRajP** [comment]
**Hi ideepsrma,**

Apologies for the delay in response.

I am glad you figured out the solution to get the code working yourself and even if it does not, the latest commit can be cloned and I believe is guaranteed to work properly

However, concerning the issue of blank screen, I used to have the same issue which was caused due to the presence of a strange hidden file in the directory where WhatsApp saves statuses.
So, to counter that issue, I had designed the app to ignore the presence of that file and continue indexing downloaded statuses.

So, when you tell me the error has occurred again, I am puzzled and unable to reproduce the error from my side as it compiles perfectly and also works on Samsung m30s which I have tried executing it on.

Could you please perform the following actions:

1. Verify that there are indeed downloaded WhatsApp statuses on device.
2. LOG different stages of _readFiles_ function to find where the error is originating from.
3. Try running the same app on a different device to check if it is device specific bug.

If the issue still persists, please do tell me about it and in the meantime, I will try to make the app have a log page that tells us the status of each operation for easy debugging on different devices without the need for an adb console.

**Comment by ideepsrma** [comment]
Hello sir ,

Now its working fine, Now am trying to add Photo / Video inbuilt viewer ,
After adding i want to contribute ....

Thankx sir..n

**Comment by RohitRajP** [comment]
**Hi ideepsrma,**

I am glad things have started to work out for you.
Could you please tell me how you managed to solve the blank screen issue?

I am super excited to hear you are building more functionality into the application, and for that I believe you can just fork the repository, and generate a pull request once you are done so that I can pull it to the main branch, credit your contribution in the "About" section and update the new application on Google Play. An inbuilt viewer would greatly improve the usability and portability of the app. Waiting to see it in action.
